[package]
name = "rust-wallet-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = {version = "1.0"}
tokio = { version = "1", features = ["full"] }
